travis:
  secure:
    BINSTAR_TOKEN: nK/BSXsvmm3iy66qtfnquW7Pzqklzyy25rdeOKsbN4fu4WQaMuEbOdh1qpLKKeeIJK6MbBWlsasD9PkD17uTgyUZQMNbQRJ2MszWbqG4ZFD3/GptgglyBVSUnJmZbx89n5q2Ud69i1um4v9HQuVBcbIsnzOHbkwx530KG18nT5xGnE77QywvfY2Pxh/fmtpy5QGoqsLEcdozwAaKd2jrFXlr+/rdoJppw6jZA6qLCO2XVIkfNPWSEVpZU4hz87pVdXH8Lwt12zmDReNiajdSyF/W0Gezp/+7oU07DTOn5KhAhjSkzQl2oXngf/px9HnAR41l7GFkpA3iIplDW9CyAEc8dcYzFVCiUDaHdQPl35kdJcj2oQzi4y3D0JvLGdwYJTqLms2gYnjFJsqnk3/6itdM8c5EKMPOBKu7bgzapu2Q8Ra1bEWcTE0h5XzGiBFD0Nh88mUXBwYHK+pHmfBrRGuYDhtsWJYI7ALUTyv69oYUeeDHoINwD7Ntyiaqgi2vlikFT9MZtJy45RH+3dIZHqvhGOKLY53/XCQMfY7xribr0Jx+mTtsJKdsBWN5MELtenGBLvqE8lLwRfgZXzBv1lveSnSfSUm6Txz9nNxb/8WAWCRkBMRNSvvryusSWZpTKP+YUlQF3VZvFWPUtdBaaYRFmb2L4xNPsJBk20qSNK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
